// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjcwdbwqjdzksoqxkfvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqY3dkYndxamR6a3NvcXhrZnZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDkxODIsImV4cCI6MjA2NTQ4NTE4Mn0.jp1xuOVeBEVH6EZ8MwjA2Wky4AREUKpx-BeRo-vLFaY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);